### PR TITLE
Wrapped plugin in a closure and unified jQuery access.

### PR DESCRIPTION
**Pull request by marijn**
Use `$` in favor of `jQuery`.

### CODE REVIEW

**Comment by marijn** [comment]
Damn it. I didn't branch of master. My other pull request (#7) is included as well by accident. Let me know if I should remove ba6e079.

**Comment by marijn** [comment]
I shouldn't send out pull requests on friday, I forgot to alias `WysiHat` to the `window` object.

**Comment by swilliams** [comment]
So, is this still valid, or should it be closed? :)

**Comment by marijn** [comment]
This has been updated and is valid.

**Pull request merged**
